package models.models;

public enum CategEnfant {
    STRUCTURE_FAMILIALR,
    DYNAMIQUE_FAMILIALE,
    ANTCEDENT_FAMILIAUX ,
    CONDITIOND_NATALS,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_COMPORTEMENT
}
